"""Data models for inbox-zero."""

from __future__ import annotations

from typing import Any
from pydantic import BaseModel, Field


class Sender(BaseModel):
    """Email sender information."""
    name: str | None = None
    email: str

    @classmethod
    def from_gws(cls, raw: Any) -> Sender:
        """Parse sender from gws output."""
        if isinstance(raw, dict):
            return cls(
                name=raw.get("name"),
                email=raw.get("email") or raw.get("address") or "unknown@unknown.com",
            )
        if isinstance(raw, str):
            # Parse 'Name <email@domain>' or just 'email@domain'
            if "<" in raw and raw.endswith(">"):
                parts = raw.split("<", 1)
                return cls(name=parts[0].strip().strip('"'), email=parts[1].rstrip(">").strip())
            return cls(email=raw.strip())
        return cls(email="unknown@unknown.com")


class CalendarEventSuggestion(BaseModel):
    """A suggested calendar event extracted from an email."""
    summary: str = Field(description="Event title / subject")
    start_time: str = Field(description="ISO-8601 formatted start datetime with timezone or YYYY-MM-DD")
    end_time: str | None = Field(default=None, description="ISO-8601 formatted end datetime")
    description: str | None = Field(default=None, description="Event description or notes")
    location: str | None = Field(default=None, description="Event location or link")


class EmailMessage(BaseModel):
    """Raw/normalized email message from Google Workspace."""
    id: str
    thread_id: str
    subject: str = "(No Subject)"
    sender: Sender
    date: str
    body_text: str = ""
    body_html: str | None = None
    snippet: str | None = None
    is_unread: bool = True


class TriageItem(BaseModel):
    """Enriched triage analysis for a conversation thread or email."""
    message_id: str = Field(description="ID of the latest/primary message in thread to reply to")
    thread_id: str = Field(description="Gmail conversation thread ID")
    sender_name: str | None = None
    sender_email: str
    date: str
    subject: str
    title_summary: str = Field(description="One-line punchy summary")
    brief_summary: str = Field(description="2-3 sentence overview of conversation")
    category: str = Field(default="General", description="Category e.g. School, Sports, Work, Newsletter")
    action_items: list[str] = Field(default_factory=list, description="Action items requiring user attention")
    calendar_events: list[CalendarEventSuggestion] = Field(
        default_factory=list, description="Extracted dates/events"
    )
    suggested_replies: list[str] = Field(
        default_factory=list, description="Suggested quick reply drafts if relevant"
    )
    raw_body_preview: str = ""
    senders: list[Sender] = Field(default_factory=list, description="All distinct senders in thread")
    messages: list[EmailMessage] = Field(default_factory=list, description="All messages in thread in chronological order")
    message_count: int = Field(default=1, description="Total messages in thread")
    unread_count: int = Field(default=1, description="Number of unread messages in thread")


class TriageBatch(BaseModel):
    """A collection of triaged items."""
    total_unread: int = Field(description="Total unread threads")
    total_messages: int = Field(default=0, description="Total messages across all threads")
    items: list[TriageItem] = Field(default_factory=list)


class AgentReplyAction(BaseModel):
    """A reply action proposed by an AI agent."""
    message_id: str
    body: str


class AgentDecisions(BaseModel):
    """Structured decisions generated by an AI agent."""
    reasoning: str | None = None
    replies: list[AgentReplyAction] = Field(default_factory=list)
    calendar_events: list[CalendarEventSuggestion] = Field(default_factory=list)
    mark_as_read: list[str] = Field(default_factory=list)

